spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clothes_mall?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace